#' Fit basic statistical models to climate data
#'
#' Fits linear regression, LOESS, or smoothing splines to hemispheric data from NASA.
#' @param obj An object of class \code{"climr"} generated by \code{\link{load_climr}}.
#' @param data_type The type of data to be modelled, either \code{"yearly"}
#' (the default), \code{"quarterly"}, or \code{"monthly"}.
#' @param fit_type The type of model required, either linear regression (\code{"lm"}) by default,
#' \code{"loess"}, or smoothing splines (\code{"smooth.spline"}).
#'
#' @return An object of class \code{"climr_fit"} which includes the model details
#' as well as the data set and \code{fit_type} used.
#'
#' @note A dedicated \code{\link{plot.climr_fit}} method is provided
#' for objects of class \code{"climr_fit"}
#' .
#' @seealso \code{\link{load_climr}}, \code{\link{plot.climr_fit}}, \code{\link[stats]{lm}},
#' \code{\link[stats]{loess}}, \code{\link[stats]{smooth.spline}}
#'
#' @export
#' @author Keefe Murphy - <\email{keefe.murphy@@mu.ie}>
#' @examples
#' dat <- load_climr(type = "SH")
#' mod1 <- fit(dat)
#' mod2 <- fit(dat, data_type="monthly", fit_type="smooth.spline")
#' mod3 <- fit(dat, data_type="quarterly", fit_type="loess")
fit <- function(obj,
                data_type = c("yearly", "quarterly", "monthly"),
                fit_type = c("lm", "loess", "smooth.spline")) {
  UseMethod("fit")
}

#' @export
fit.climr <- function(obj,
                      data_type = c("yearly", "quarterly", "monthly"),
                      fit_type = c("lm", "loess", "smooth.spline")) {

  ## Find out which data set to use
  data_type <- match.arg(data_type)

  ## Find out what type of fitting method to use
  fit_type <- match.arg(fit_type)

  ## Find out which bit of the data to use and get it
  dat_choose <- switch(data_type,
                       yearly = "clim_year",
                       quarterly = "clim_quarter",
                       monthly = "clim_month")
  dat <- obj[[dat_choose]]

  ## Fit some models
  mod <- switch(fit_type,
                lm = {
                  dat |> lm(temp ~ x, data=_)
                },
                loess = {
                  dat |> loess(temp ~ x, data=_)
                },
                smooth.spline = {
                  dat |> (\(x) smooth.spline(x$x, x$temp))()
                })
  print(mod)

  ## Output so it can be plotted
  output <- list(model = mod,
                 data = dat,
                 data_type = data_type,
                 fit_type = fit_type)
  attr(output, "source") <- attr(obj, "source")
  class(output) <- c("climr_fit", "listof")
  invisible(output)
}
